services:
  client:
    build: ../../../../../../Users/ASUS/AppData/Local/Temp/Rar$DRa4684.39547/task-management-main
    ports:
      - "5000:8080"
    volumes:
      - .:/app
    command: ["npm", "run", "serve"]
